#!/bin/bash
set -euo pipefail

function log_color() {
  local color_code="$1"
  shift

  printf "\033[${color_code}m%s\033[0m\n" "$*" >&2
}

function log_red() {
  log_color "0;31" "$@"
}

function log_blue() {
  log_color "0;34" "$@"
}

function log_green() {
  log_color "1;32" "$@"
}

function log_yellow() {
  log_color "1;33" "$@"
}

function log_task() {
  log_blue "⏳" "$@"
}

function log_manual_action() {
  log_red "🧑‍🔧" "$@"
}

function log_c() {
  log_yellow "👉" "$@"
}

function c() {
  log_c "$@"
  "$@"
}

function c_exec() {
  log_c "$@"
  exec "$@"
}

function log_error() {
  log_red "🔴" "$@"
}

function log_info() {
  log_green "💡" "$@"
}

function error() {
  log_error "$@"
  exit 1
}

log_task "Installing APT prerequisites"

# We need to install ca-certificates before we add the APT repos, because some of them
# may use newer CAs.
# Ignore apt update error if it is due to expired certificate because chances are that
# the next command will fix it.
if output="$(apt-get update --yes)" || [[ "${output}" == *"The certificate chain uses expired certificate."* ]]; then
  echo "${output}"
  true
else
  echo "${output}"
  exit 1
fi
c apt-get install --yes -qq -o=Dpkg::Use-Pty=0 --no-install-recommends ca-certificates
c apt-get install --yes -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl wget gnupg \
  sudo software-properties-common zsh locales locales-all jq gettext autoconf apt-transport-https zip bzip2 unzip

# Add APT repositories for newer versions of Git.
# This is required for git to use signing keys with ed25519 algorithm.
# It means that we can use the same SSH key for authentication and signing commits.
# remove existing apt sources
c rm -f etc/apt/sources.list.d/git-core-*.list*
c add-apt-repository ppa:git-core/ppa --yes
c apt-get update --yes
c apt-get install --yes -qq -o=Dpkg::Use-Pty=0 --no-install-recommends git

# Set up locales
# check if locale is already set up by running locale | grep LC_ALL | grep en_US.UTF-8
if ! locale | grep LC_ALL | grep -q en_US.UTF-8; then
  log_task "Setting up locales"
  c locale-gen en_US en_US.UTF-8 || true
  c localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 || true
fi
